version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: quake3
    volumes:
      - ./src/configurations/setup-database.js:/docker-entrypoint-initdb.d/setup-database.js:ro
    networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge
